
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install -g terser csso-cli html-minifier-terser

      - name: Prepare dist folder
        run: |
          rm -rf dist
          mkdir dist
          shopt -s extglob
          cp -r !(dist|.git|.github) dist/

      - name: Minify CSS
        run: |
          find dist -type f -name "*.css" ! -name "*.min.css" | while read css; do
            csso "$css" --output "$css"
          done

      - name: Minify JS
        run: |
          find dist -type f -name "*.js" ! -name "*.min.js" | while read js; do
            terser "$js" -o "$js" -c -m
          done

      - name: Minify HTML
        run: |
          find dist -type f -name "*.html" | while read html; do
            html-minifier-terser \
              --collapse-whitespace \
              --remove-comments \
              --remove-redundant-attributes \
              --remove-script-type-attributes \
              --remove-style-link-type-attributes \
              --use-short-doctype \
              --minify-css true \
              --minify-js true \
              --ignore-custom-comments "^\[if|^\/|^google|^\/google" \
              -o "$html" "$html"
          done

      - name: Compress Images to WebP (keep originals)
        run: |
          if ! command -v cwebp &> /dev/null; then
            sudo apt-get update && sudo apt-get install -y webp
          fi
          find dist -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) | while read img; do
            cwebp -q 80 "$img" -o "${img%.*}.webp" || true
          done

      - name: Update HTML to use WebP with fallback
        run: |
          find dist -type f -name "*.html" | while read html; do
            # Cari semua <img> dan ubah jadi <picture> + fallback
            perl -0777 -i -pe '
              s#<img([^>]*?)src="([^"]+)\.(jpg|jpeg|png)"([^>]*)>#<picture><source srcset="\2.webp" type="image/webp"><img\1src="\2.\3"\4></picture>#gi
            ' "$html"
          done

      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: site-files
          path: dist

      - name: Download build files
        uses: actions/download-artifact@v4
        with:
          name: site-files
          path: dist
